### ISSUE TITLE
[Home] 홈 페이지 마크업, 스타일링

### ISSUE THREAD

**Issue by dongapple** [FRONTENDSCHOOL6/Pet_Bridge#24]
## 👩‍💻 상세 내용 
 

![Image](https://github.com/FRONTENDSCHOOL6/Pet_Bridge/assets/74224516/7ee05187-e8aa-44de-95d3-edd6c7f9f3d0)

  - page : home
  - about : home 페이지 마크업 구현

<br>

## 📝 Todo 
  - [x] 누적후원금액 컴포넌트 구현
  - [x] 배너 컴포넌트 구현
    - [x] 포켓베이스 연동
    - [x] 베너 이미지 제작
    - [x] 스와이퍼 기능 추가 
  - [x] 후원 신청 섹션 구현
    - [x] 메일 기능 추가 
  - [x] 보호센터 소개 컴포넌트 구현
    - [x] 포켓베이스 연동
    - [x] 아이템 컴포넌트 구현
    - [x] 스와이퍼 기능 추가

</b>
</br>

## 🎸 ETC

- 기타 설명이 필요하면 적어주고 스크린샷이 필요한 경우 아래에 첨부해주세요

:camera: 스크린샷
