### ISSUE TITLE
[place] Map.jsx 생성

### ISSUE THREAD

**Issue by tuna7797** [FRONTENDSCHOOL6/Pet_Bridge#36]
## 👩‍💻 상세 내용 
 
  - page : Place.jsx 에서 내 주변 보호소 찾기 클릭시 이동하는 지도 페이지
  - about : 페이지 생성 및 지도 api를 호출할 레이아웃 구현

<br>

## 📝 Todo 
  - [x] Map.jsx 파일 생성
  - [x] Place.jsx 내 주변 보호소 찾기 버튼과 연동
  - [x]  내 주변 보호소 페이지 마크업
  - [x] 스타일링 필요한 경우 지도 삽입후 추가 예정

</b>
</br>

## 🎸 ETC

:camera: 스크린샷

![image](https://github.com/FRONTENDSCHOOL6/Pet_Bridge/assets/87564155/ef4c0543-abfd-43ee-a833-c27de9a5db64)
