### ISSUE TITLE
[Place] 유기동물 봉사활동 페이지 상세 기능 구현

### ISSUE THREAD

**Issue by tuna7797** [FRONTENDSCHOOL6/Pet_Bridge#39]
## 👩‍💻 상세 내용 
 
  - page : 유기동물 봉사활동 (Place.jsx)
  - about : 페이지 내 링크 / 전화하기 / 위치보기 등 구현

<br>

## 📝 Todo 
  - [x] 내 주변 보호소 찾기 클릭시 Map.jsx로 이동
  - [x] 추천 보호소 영역 전화하기 클릭시 전화연결
  - [x] 추천 보호소 영역 위치보기 클릭시 모달 내부 지도 api 연동
  - [x] 보호소 목록 사이트 url 연동

</b>
</br>

## 🎸 ETC

:camera: 스크린샷
