### ISSUE TITLE
[SignUp] 회원가입 페이지 제작

### ISSUE THREAD

**Issue by tuna7797** [FRONTENDSCHOOL6/Pet_Bridge#53]
## 👩‍💻 상세 내용 
 
  - page : 회원가입 페이지
  - about : 회원가입 페이지 생성
<br>

## 📝 Todo 
  - [x] 회원가입 페이지 디자인
  - [x] SignUp.jsx 생성
  - [x] 회원가입 페이지 마크업
  - [x] tailwind로 스타일링

</b>
</br>

## 🎸 ETC

:camera: 스크린샷
