### ISSUE TITLE
[SignUp] 회원가입 페이지 기능 구현

### ISSUE THREAD

**Issue by tuna7797** [FRONTENDSCHOOL6/Pet_Bridge#72]
## 👩‍💻 상세 내용 
 
  - page : 회원가입 페이지
  - about : 회원가입 페이지 상세 기능 구현

<br>

## 📝 Todo 
  - [x] 정규식 표현으로 회원가입 폼 유효성 검사
  - [x] fontawesome 패키지 추가하여 아이콘 표시
  - [x] pb user 데이터와 연동
  - [x] 각 버튼별 Link 연결

</b>
</br>

## 🎸 ETC

:camera: 스크린샷
