### ISSUE TITLE
[MyPage] 마이 페이지 제작

### ISSUE THREAD

**Issue by tuna7797** [FRONTENDSCHOOL6/Pet_Bridge#73]
## 👩‍💻 상세 내용 
 
  - page : 마이 페이지
  - about : 로그인 했을시 접근가능한 마이페이지 추가
<br>

## 📝 Todo 
  - [x] 마이 페이지 디자인
  - [x] MyPage.jsx 생성
  - [x] 마이 페이지 마크업
  - [x] tailwind로 스타일링

</b>
</br>

## 🎸 ETC

:camera: 스크린샷
